export const LOGIN_BUTTON_CLICKED = "LOGIN_BUTTON_CLICKED";
export const RESET_PASSWORD_BUTTON_CLICKED = "RESET_PASSWORD_BUTTON_CLICKED";

export const POPUP_VIEW_BUTTON_CLICKED = "POPUP_VIEW_BUTTON_CLICKED";
export const POPUP_CLOSE_BUTTON_CLICKED = "POPUP_CLOSE_BUTTON_CLICKED";

export const VIEW_EDIT_BUTTON_CLICKED = "VIEW_EDIT_BUTTON_CLICKED";
export const VIEW_EDIT_CLOSE_BUTTON_CLICKED = "VIEW_EDIT_CLOSE_BUTTON_CLICKED";

export const VIEW_REPORT_BUTTON_CLICKED = "VIEW_REPORT_BUTTON_CLICKED";
export const VIEW_REPORT_CLOSE_BUTTON_CLICKED = "VIEW_REPORT_CLOSE_BUTTON_CLICKED";

export const VIEW_CONFIRM_CASE_BUTTON_CLICKED = "VIEW_CONFIRM_CASE_BUTTON_CLICKED"
export const VIEW_CONFIRM_CASE_CLOSE_BUTTON_CLICKED = "VIEW_CONFIRM_CASE_CLOSE_BUTTON_CLICKED"

export const VIEW_SINGLE_CASE_BUTTON_CLICKED = "VIEW_SINGLE_CASE_BUTTON_CLICKED"
export const VIEW_SINGLE_CASE_CLOSE_BUTTON_CLICKED = "VIEW_SINGLE_CASE_CLOSE_BUTTON_CLICKED"

export const VIEW_ASSIGN_PHI_BUTTON_CLICKED = "VIEW_ASSIGN_PHI_BUTTON_CLICKED"
export const VIEW_ASSIGN_PHI_BUTTON_CLOSE_BUTTON_CLICKED = "VIEW_ASSIGN_PHI_BUTTON_CLOSE_BUTTON_CLICKED"

export const VIEW_UN_ASSIGN_CASE_BUTTON_CLICKED = "VIEW_UN_ASSIGN_CASE_BUTTON_CLICKED"
export const VIEW_UN_ASSIGN_CASE_BUTTON_CLOSE_BUTTON_CLICKED = "VIEW_UN_ASSIGN_CASE_BUTTON_CLOSE_BUTTON_CLICKED"

export const VIEW_ASSIGN_MOH_BUTTON_CLICKED = "VIEW_ASSIGN_MOH_BUTTON_CLICKED"
export const VIEW_ASSIGN_MOH_BUTTON_CLOSE_BUTTON_CLICKED = "VIEW_ASSIGN_MOH_BUTTON_CLOSE_BUTTON_CLICKED"

export const VIEW_EDIT_EVENT_BUTTON_CLICKED = "VIEW_EDIT_EVENT_BUTTON_CLICKED"
export const VIEW_EDIT_EVENT_CLOSE_BUTTON_CLICKED = "VIEW_EDIT_EVENT_CLOSE_BUTTON_CLICKED"

export const VIEW_ADD_NEW_CASE_BUTTON_CLICKED = "VIEW_ADD_NEW_CASE_BUTTON_CLICKED"
export const VIEW_ADD_NEW_CASE_CLOSE_BUTTON_CLICKED = "VIEW_ADD_NEW_CASE_CLOSE_BUTTON_CLICKED"

export const REPORT_SEND_BUTTON_CLICKED = "REPORT_SEND_BUTTON_CLICKED"


