export const LOGIN_BUTTON_CLICKED = "LOGIN_BUTTON_CLICKED";
export const POPUP_VIEW_BUTTON_CLICKED = "POPUP_VIEW_BUTTON_CLICKED";
export const POPUP_CLOSE_BUTTON_CLICKED = "POPUP_CLOSE_BUTTON_CLICKED";