export const LOGIN_BUTTON_CLICKED = "LOGIN_BUTTON_CLICKED";

export const POPUP_VIEW_BUTTON_CLICKED = "POPUP_VIEW_BUTTON_CLICKED";
export const POPUP_CLOSE_BUTTON_CLICKED = "POPUP_CLOSE_BUTTON_CLICKED";

export const VIEW_EDIT_BUTTON_CLICKED = "VIEW_EDIT_BUTTON_CLICKED";
export const VIEW_EDIT_CLOSE_BUTTON_CLICKED = "VIEW_EDIT_CLOSE_BUTTON_CLICKED";